language: r
r:
  - release
sudo: false
cache: packages

matrix:
  include:
    - os: linux
      dist: trusty
      sudo: required
      env:
        global:
          - R_LIBS="http://cran.rstudio.com"
after_success:
  - sudo apt-get install sendmail
  - echo -e "testestest"

language: php
