language: r
r:
  - release


matrix:
  include:
    - os: linux
      dist: trusty
      sudo: required
      env:
        global:
          - R_LIBS="http://cran.rstudio.com"
after_success:
  - echo -e "testestest"
  - /usr/lib/sm.bin/sendmail romanflury@hotmail.com < test.txt