image: alpine:latest

pages:
  stage: deploy
  script:
  - echo -e 'build & check spam with a stable R version'
  - echo -e '  export environment variables to have CRAN like conditions'
  - mail -s "hi" fluryro@gmail.com <<< "how are you?"<br>
  only:
  - master
