language: r
r:
  - release


matrix:
  include:
    - os: linux
      dist: trusty
      sudo: required
      env:
        global:
          - R_LIBS="http://cran.rstudio.com"
after_success:
  - echo -e "testestest"
  - Rscript 'test.R' 2>&1 | mail -s "test" romanflury@hotmail.com 
